"""
Creates AI_Finder_Script.docx using only Python built-ins (zipfile + io).
No pip install required.
"""
import zipfile, io, os

OUT = r"C:\Users\HI\Desktop\MY CODESPACE\Ai Finder\AI_Finder_Script.docx"

# ── colour helpers ────────────────────────────────────────────────────────────
def xml(s): return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

# ── paragraph builders ────────────────────────────────────────────────────────
def para(runs, spacing_before=100, spacing_after=100, indent=0, shade=None, border_left=None):
    pPr = f'<w:spacing w:before="{spacing_before}" w:after="{spacing_after}"/>'
    if indent: pPr += f'<w:ind w:left="{indent}"/>'
    if shade:  pPr += f'<w:shd w:val="clear" w:color="auto" w:fill="{shade}"/>'
    if border_left:
        pPr += f'<w:pBdr><w:left w:val="single" w:sz="{border_left[0]}" w:space="4" w:color="{border_left[1]}"/></w:pBdr>'
    body = ''.join(runs)
    return f'<w:p><w:pPr>{pPr}</w:pPr>{body}</w:p>'

def run(text, bold=False, italic=False, color="1F2937", size=22):
    rPr = f'<w:sz w:val="{size}"/><w:szCs w:val="{size}"/><w:color w:val="{color}"/><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>'
    if bold:   rPr += '<w:b/>'
    if italic: rPr += '<w:i/>'
    return f'<w:r><w:rPr>{rPr}</w:rPr><w:t xml:space="preserve">{xml(text)}</w:t></w:r>'

def empty(): return '<w:p><w:pPr><w:spacing w:before="80" w:after="80"/></w:pPr></w:p>'

def rule():
    return '<w:p><w:pPr><w:spacing w:before="160" w:after="160"/><w:pBdr><w:bottom w:val="single" w:sz="4" w:space="1" w:color="D1D5DB"/></w:pBdr></w:pPr></w:p>'

def title_para(text, size, color, bold=True, italic=False):
    rPr = f'<w:sz w:val="{size}"/><w:szCs w:val="{size}"/><w:color w:val="{color}"/><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>'
    if bold: rPr += '<w:b/>'
    if italic: rPr += '<w:i/>'
    return f'<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:before="0" w:after="80"/></w:pPr><w:r><w:rPr>{rPr}</w:rPr><w:t>{xml(text)}</w:t></w:r></w:p>'

def scene(text):
    return para(
        [run(f"  {text}", bold=True, color="7C3AED", size=22)],
        spacing_before=280, spacing_after=80,
        shade="EDE9FE", border_left=(18, "7C3AED")
    )

def dialog(speaker, line_text):
    return para(
        [run(f"{speaker}:  ", bold=True, color="1F2937", size=22),
         run(line_text, color="1F2937", size=22)],
        spacing_before=100, spacing_after=100, indent=400
    )

def stage(text):
    return para(
        [run(f"[ {text} ]", italic=True, color="6B7280", size=20)],
        spacing_before=60, spacing_after=60, indent=400
    )

def note(text):
    return para(
        [run(f"  {text}", italic=True, color="6B7280", size=20)],
        spacing_before=60, spacing_after=60, indent=400
    )

# ── document body ─────────────────────────────────────────────────────────────
body_parts = [
    # TITLE BLOCK
    title_para("AI FINDER", 52, "7C3AED"),
    title_para("Presentation Video Script", 32, "1F2937"),
    title_para("2-Person  ·  Full English  ·  School Computer Lab with Big TV", 22, "6B7280", bold=False),
    title_para("Digital Fest 2026  ·  Social Media Impact (10 marks)", 20, "6B7280", bold=False, italic=True),
    f'<w:p><w:pPr><w:spacing w:before="200" w:after="200"/></w:pPr></w:p>',
    rule(),

    # SCENE 1
    scene("SCENE 1 — OPENING  [ Both on camera · TV shows AI Finder homepage ]"),
    empty(),
    dialog("Person A", "Hey everyone. We’re here to show you something we built — and honestly, it’s something the internet actually needs right now."),
    dialog("Person B", "It’s called AI Finder. It detects whether an image was generated by AI — or taken by a real human."),
    rule(),

    # SCENE 2
    scene("SCENE 2 — LIVE DEMO  [ Person B at keyboard · Person A explaining ]"),
    empty(),
    dialog("Person A", "So here’s how it works. We go to our website — aifinder-phi.vercel.app — and we drop in any image."),
    stage("Person B types / pastes an image URL and clicks Analyze"),
    dialog("Person B", "Let’s try this one. We hit Analyze..."),
    dialog("Person A", "And within seconds, the system scans it. It’s looking at four things — artificial patterns, noise consistency, semantic coherence, and metadata anomalies."),
    stage("Result appears on the big TV — score shows 94% AI Generated"),
    dialog("Person B", "There it is. 94% AI Generated. The heatmap even shows you where in the image the AI signals are strongest."),
    rule(),

    # SCENE 3
    scene("SCENE 3 — TECH EXPLANATION  [ Both standing near the TV ]"),
    empty(),
    dialog("Person A", "Under the hood, we’re using a vision AI model to analyze the pixel-level structure of the image. Real photos have natural imperfections — grain, lighting inconsistencies. AI images don’t."),
    dialog("Person B", "We built the backend as a serverless function on Vercel, and the frontend in React. The whole thing runs in the cloud — no installation needed."),
    rule(),

    # SCENE 4
    scene("SCENE 4 — EXPLAIN PANEL  [ Person B clicks · Person A explains ]"),
    empty(),
    dialog("Person B", 'And if you want to understand why it got that score — you click "Get Detailed AI Analysis."'),
    dialog("Person A", "It breaks down each signal. Like — Artificial Patterns scored high, meaning the textures are too smooth, too perfect. That’s a classic AI tell."),
    rule(),

    # SCENE 5
    scene("SCENE 5 — CLOSING  [ Both on camera · website URL on TV ]"),
    empty(),
    dialog("Person A", "In a world where deepfakes and AI art are everywhere, people need a fast, free way to verify what’s real."),
    dialog("Person B", "That’s what AI Finder does. Built by us, for everyone."),
    dialog("Person A", "Try it yourself — aifinder-phi.vercel.app"),
    dialog("Person B", "(smiles)  If it says 94%... it’s not real."),
    stage("Both look at camera — end card with website URL displayed on TV behind them"),
    rule(),

    # PRODUCTION NOTES
    scene("PRODUCTION NOTES"),
    empty(),
    note("⏱  Estimated length: 1.5 – 2.5 minutes depending on demo speed"),
    note("⏱  Keep the demo slow and clear so the TV audience can follow along"),
    note("⏱  Person B should have the browser open and ready before recording"),
    note("⏱  Use an Unsplash image URL for demo — Wikimedia URLs may block"),
    note("⏱  Stand slightly to the side so the result score is visible on TV"),
    note("⏱  Upload video to social media for the Social Media Impact marks"),
]

doc_xml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
 xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
 xmlns:v="urn:schemas-microsoft-com:vml"
 xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"
 xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
 xmlns:w10="urn:schemas-microsoft-com:office:word"
 xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
 xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"
 xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup"
 xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk"
 xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"
 xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"
 mc:Ignorable="w14 wp14">
<w:body>
''' + '\n'.join(body_parts) + '''
<w:sectPr>
  <w:pgSz w:w="11906" w:h="16838"/>
  <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
</w:sectPr>
</w:body>
</w:document>'''

rels_xml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>'''

styles_xml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
        <w:color w:val="1F2937"/>
      </w:rPr>
    </w:rPrDefault>
  </w:docDefaults>
</w:styles>'''

content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>'''

root_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>'''

# ── write zip ─────────────────────────────────────────────────────────────────
buf = io.BytesIO()
with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels",         root_rels)
    z.writestr("word/document.xml",   doc_xml.encode('utf-8'))
    z.writestr("word/styles.xml",     styles_xml)
    z.writestr("word/_rels/document.xml.rels", rels_xml)

with open(OUT, 'wb') as f:
    f.write(buf.getvalue())

print(f"Done! Saved to: {OUT}")
