const {
  Document, Packer, Paragraph, TextRun, AlignmentType,
  HeadingLevel, BorderStyle, ShadingType
} = require('docx');
const fs = require('fs');

const PURPLE = "7C3AED";
const LIGHT_PURPLE = "EDE9FE";
const DARK = "1F2937";
const GREY = "6B7280";

function heading(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 320, after: 160 },
    children: [new TextRun({ text, bold: true, color: PURPLE, size: 28, font: "Arial" })]
  });
}

function sceneHeading(text) {
  return new Paragraph({
    spacing: { before: 280, after: 100 },
    shading: { fill: LIGHT_PURPLE, type: ShadingType.CLEAR },
    border: { left: { style: BorderStyle.SINGLE, size: 16, color: PURPLE } },
    indent: { left: 180, right: 180 },
    children: [new TextRun({ text: `  ${text}`, bold: true, color: PURPLE, size: 22, font: "Arial" })]
  });
}

function dialogLine(speaker, line) {
  return new Paragraph({
    spacing: { before: 100, after: 100 },
    indent: { left: 360 },
    children: [
      new TextRun({ text: `${speaker}:  `, bold: true, color: DARK, size: 22, font: "Arial" }),
      new TextRun({ text: line, color: DARK, size: 22, font: "Arial" }),
    ]
  });
}

function direction(text) {
  return new Paragraph({
    spacing: { before: 80, after: 80 },
    indent: { left: 360 },
    children: [
      new TextRun({ text: `[${text}]`, italics: true, color: GREY, size: 20, font: "Arial" }),
    ]
  });
}

function divider() {
  return new Paragraph({
    spacing: { before: 200, after: 200 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "D1D5DB" } },
    children: []
  });
}

function tip(text) {
  return new Paragraph({
    spacing: { before: 80, after: 80 },
    indent: { left: 360 },
    children: [new TextRun({ text: `⏱  ${text}`, color: GREY, size: 20, italics: true, font: "Arial" })]
  });
}

const doc = new Document({
  styles: {
    default: {
      document: { run: { font: "Arial", size: 22, color: DARK } }
    },
    paragraphStyles: [
      {
        id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal",
        quickFormat: true,
        run: { size: 28, bold: true, font: "Arial", color: PURPLE },
        paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 0 }
      }
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width: 11906, height: 16838 }, // A4
        margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }
      }
    },
    children: [
      // Title block
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 0, after: 80 },
        children: [new TextRun({ text: "AI FINDER", bold: true, size: 48, color: PURPLE, font: "Arial" })]
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 0, after: 80 },
        children: [new TextRun({ text: "Presentation Video Script", bold: true, size: 30, color: DARK, font: "Arial" })]
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 0, after: 60 },
        children: [new TextRun({ text: "2-Person · Full English · School Computer Lab", size: 22, color: GREY, font: "Arial" })]
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 0, after: 320 },
        children: [new TextRun({ text: "Digital Fest 2026  ·  Social Media Impact (10 marks)", italics: true, size: 20, color: GREY, font: "Arial" })]
      }),

      divider(),

      // ── SCENE 1 ────────────────────────────────────────────────────────────
      sceneHeading("SCENE 1 — OPENING  [Both on camera · TV shows AI Finder homepage]"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      dialogLine("Person A",
        "Hey everyone. We're here to show you something we built — and honestly, it's something the internet actually needs right now."),

      dialogLine("Person B",
        "It's called AI Finder. It detects whether an image was generated by AI — or taken by a real human."),

      divider(),

      // ── SCENE 2 ────────────────────────────────────────────────────────────
      sceneHeading("SCENE 2 — LIVE DEMO  [Person B at keyboard · Person A explaining]"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      dialogLine("Person A",
        "So here's how it works. We go to our website — aifinder-phi.vercel.app — and we drop in any image."),

      direction("Person B types / pastes an image URL and clicks Analyze"),

      dialogLine("Person B", "Let's try this one. We hit Analyze..."),

      dialogLine("Person A",
        "And within seconds, the system scans it. It's looking at four things — artificial patterns, noise consistency, semantic coherence, and metadata anomalies."),

      direction("Result appears on the big TV — score shows 94% AI Generated"),

      dialogLine("Person B",
        "There it is. 94% AI Generated. The heatmap even shows you where in the image the AI signals are strongest."),

      divider(),

      // ── SCENE 3 ────────────────────────────────────────────────────────────
      sceneHeading("SCENE 3 — TECH EXPLANATION  [Both standing near the TV]"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      dialogLine("Person A",
        "Under the hood, we're using a vision AI model to analyze the pixel-level structure of the image. Real photos have natural imperfections — grain, lighting inconsistencies. AI images don't."),

      dialogLine("Person B",
        "We built the backend as a serverless function on Vercel, and the frontend in React. The whole thing runs in the cloud — no installation needed."),

      divider(),

      // ── SCENE 4 ────────────────────────────────────────────────────────────
      sceneHeading("SCENE 4 — EXPLAIN PANEL  [Person B clicks · Person A explains]"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      dialogLine("Person B", 'And if you want to understand why it got that score — you click "Get Detailed AI Analysis."'),

      dialogLine("Person A",
        "It breaks down each signal. Like — Artificial Patterns scored high, meaning the textures are too smooth, too perfect. That's a classic AI tell."),

      divider(),

      // ── SCENE 5 ────────────────────────────────────────────────────────────
      sceneHeading("SCENE 5 — CLOSING  [Both on camera · website URL on TV]"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      dialogLine("Person A",
        "In a world where deepfakes and AI art are everywhere, people need a fast, free way to verify what's real."),

      dialogLine("Person B", "That's what AI Finder does. Built by us, for everyone."),

      dialogLine("Person A", "Try it yourself — aifinder-phi.vercel.app"),

      dialogLine("Person B", "(smiles)  If it says 94%... it's not real."),

      direction("Both look at camera — end card with website URL displayed on TV behind them"),

      divider(),

      // ── TIPS ──────────────────────────────────────────────────────────────
      sceneHeading("PRODUCTION NOTES"),

      new Paragraph({ spacing: { before: 140, after: 60 }, children: [] }),

      tip("Estimated length: 1.5 – 2.5 minutes depending on demo speed"),
      tip("Keep the demo part slow and clear so the TV audience can follow along"),
      tip("Person B should have the browser open and ready before recording starts"),
      tip("Use an Unsplash image URL for demo — Wikimedia URLs can give errors"),
      tip("Stand slightly to the side when near the TV so results are visible"),
    ]
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync("C:\\Users\\HI\\Desktop\\MY CODESPACE\\Ai Finder\\AI_Finder_Script.docx", buf);
  console.log("Done! Saved → AI_Finder_Script.docx");
});
