export default async function handler(req, res) {
<<<<<<< HEAD
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const { messages, max_tokens } = req.body;

    const systemPrompt = `You are an AI-generated image detection expert with vision capabilities. Analyze images carefully and return ONLY a valid JSON object with no extra text or markdown.

CRITICAL DETECTION RULES (apply in order):
1. WATERMARKS: If you see any text watermark VISIBLY INSIDE the image like "Gemini", "Google AI", "ImageFX", "DALL-E", "DALL·E", "Midjourney", "Stable Diffusion", "Adobe Firefly", "Sora", "Created with AI", "Generated by AI" → set verdict="AI-Generated" and overallScore=97 immediately.
2. FACES: Hyper-smooth plastic skin, glassy eyes, impossible symmetry, perfect studio lighting = AI signal.
3. HANDS: Wrong number of fingers, fused/extra fingers, bent unnaturally = strong AI artifact.
4. BACKGROUNDS: Melting textures, smeared details, objects merging together, nonsense patterns = AI artifact.
5. TEXT IN IMAGE: Garbled, fake, or nonsense text floating in the image = AI artifact.
6. REAL PHOTOS: Natural grain/noise, real lens imperfections, authentic motion blur, natural shadows = score 5-25. Do NOT penalize professional photography.

SCORING: overallScore = probability the image is AI-generated (integer 0-100, or -1 for unanalyzable URLs).
- verdict="AI-Generated" when overallScore is 60-100
- verdict="Uncertain" when overallScore is 30-59
- verdict="Likely Real" when overallScore is 0-29
- verdict="Cannot analyze URL" and overallScore=-1 ONLY for YouTube/TikTok/Instagram video page URLs
- Real camera photos should score 5-25. Only score 60+ if you see CLEAR AI artifacts.

HEATMAP: Always provide exactly 6 heatRegions covering the ENTIRE image. Use x,y,w,h as fractions 0.0-1.0.
level must be: "high" (definite AI artifact), "medium" (suspicious), or "low" (looks authentic).
MANDATORY HEATMAP CONSISTENCY - follow exactly:
- If overallScore >= 60: at least 3 regions MUST be "high" or "medium". Never mark all regions "low" when score >= 60.
- If overallScore 30-59: at least 2 regions should be "medium".
- If overallScore < 30: most regions "low", at most 1 "medium".

Return ONLY this exact JSON structure (no markdown, no explanation outside JSON):
{
  "verdict": "AI-Generated",
  "overallScore": 85,
  "signals": {
    "artificialPatterns": 80,
    "noiseConsistency": 70,
    "semanticCoherence": 75,
    "metadataAnomalies": 60
  },
  "signalTags": ["smooth skin texture", "perfect lighting", "background artifacts", "uncanny symmetry"],
  "explanation": "First sentence about main evidence. Second sentence about specific artifacts found. Third sentence about overall assessment.",
  "heatRegions": [
    {"x": 0.0, "y": 0.0, "w": 0.5, "h": 0.5, "label": "top-left", "level": "high"},
    {"x": 0.5, "y": 0.0, "w": 0.5, "h": 0.5, "label": "top-right", "level": "medium"},
    {"x": 0.0, "y": 0.33, "w": 0.5, "h": 0.34, "label": "middle-left", "level": "low"},
    {"x": 0.5, "y": 0.33, "w": 0.5, "h": 0.34, "label": "middle-right", "level": "medium"},
    {"x": 0.0, "y": 0.67, "w": 0.5, "h": 0.33, "label": "bottom-left", "level": "low"},
    {"x": 0.5, "y": 0.67, "w": 0.5, "h": 0.33, "label": "bottom-right", "level": "low"}
  ],
  "likelyTool": {
    "name": "Unknown",
    "confidence": 50,
    "reasoning": "One sentence explaining why this tool was identified or not."
  }
}`;

    // Convert messages to Anthropic format
    const anthropicMessages = [];

    for (const msg of messages) {
      if (typeof msg.content === "string") {
        anthropicMessages.push({ role: msg.role, content: msg.content });
      } else if (Array.isArray(msg.content)) {
        const parts = [];
        for (const block of msg.content) {
          if (block.type === "text") {
            parts.push({ type: "text", text: block.text });
          } else if (block.type === "image" && block.source) {
            if (block.source.type === "base64") {
              parts.push({
                type: "image",
                source: {
                  type: "base64",
                  media_type: block.source.media_type || "image/jpeg",
                  data: block.source.data
                }
              });
            } else if (block.source.type === "url") {
              parts.push({
                type: "image",
                source: {
                  type: "url",
                  url: block.source.url
                }
              });
            }
          }
        }
        anthropicMessages.push({ role: msg.role, content: parts });
      }
    }

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        system: systemPrompt,
        messages: anthropicMessages,
        max_tokens: max_tokens || 2000
      })
    });

    const data = await response.json();

    if (data.error) {
      console.error("Anthropic API error:", data.error);
      return res.status(500).json({ error: data.error.message });
    }

    const text = data.content?.[0]?.text || "";
    return res.status(200).json({ content: [{ type: "text", text }] });

  } catch (error) {
    return res.status(500).json({ error: "Analysis failed: " + error.message });
=======
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    if (req.method === "OPTIONS") return res.status(200).end();
    if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
        const { messages, max_tokens } = req.body;

      const systemPrompt = `You are an AI-generated image detection expert with vision capabilities. Analyze images carefully and return ONLY a valid JSON object with no extra text or markdown.

      CRITICAL DETECTION RULES (apply in order):
      1. WATERMARKS: If you see any text watermark inside the image like "Gemini", "hGoogle AI", "ImageFX", "DALL-E", "DALL-E", "Midjourney", "Stable Diffusion", "Adobe Firefly", "Sora", "Created with AI", "Generated by AI" set verdict="AI-Generated" and overallScore=97 immediately.
      2. FACES: Hyper-smooth plastic skin, glassy eyes, impossible symmetry, perfect studio lighting = AI signal.
      3. HANDS: Wrong number of fingers, fused/extra fingers, bent unnaturally = strong AI artifact.
      4. BACKGROUNDS: Melting textures, smeared details, objects merging together, nonsense patterns = AI artifact.
      5. TEXT IN IMAGE: Garbled, fake, or nonsense text floating in the image = AI artifact.
      6. REAL PHOTOS: Natural grain, lens imperfections, authentic motion blur, natural shadows = score 5-25. Do NOT flag professional photography as AI.

      SCORING: overallScore = probability the image is AI-generated (integer 0-100, or -1 for unanalyzable URLs).
      - verdict="AI-Generated" when overallScore is 60-100
      - verdict="Uncertain" when overallScore is 30-59
      - verdict="Likely Real" when overallScore is 0-29
      - verdict="Cannot analyze URL" and overallScore=-1 ONLY for YouTube/TikTok/Instagram video page URLs- Real camera photos score 5-25. Only score 60+ for CLEAR AI artifacts.

      HEATMAP: Always provide exactly 6 heatRegions covering the ENTIRE image. Use x,y,w,h as fractions 0.0-1.0.
      level must be: "high" (AI artifact), "medium" (suspicious), or "low" (looks authentic).
      The heatRegion levels MUST be consistent with the overallScore:
      - If overallScore >= 60: at least 3 regions MUST be "high" or "medium". NEVER mark all regions "low" when score is 60+.
      - If overallScore < 30, most regions should be "low"

      Return ONLY this exact JSON structure (no markdown, no explanation outside JSON):
      {
        "verdict": "AI-Generated",
          "overallScore": 85,
            "signals": {
                "artificialPatterns": 80,
                    "noiseConsistency": 70,
                        "semanticCoherence": 75,
                            "metadataAnomalies": 60
                              },
                                "signalTags": ["smooth skin texture", "perfect lighting", "background artifacts", "uncanny symmetry"],
                                  "explanation": "First sentence about main evidence. Second sentence about specific artifacts found. Third sentence about overall assessment.",
                                    "heatRegions": [
                                        {"x": 0.0, "y": 0.0, "w": 0.5, "h": 0.5, "label": "top-left", "level": "high"},
                                            {"x": 0.5, "y": 0.0, "w": 0.5, "h": 0.5, "label": "top-right", "level": "medium"},
                                                {"x": 0.0, "y": 0.33, "w": 0.5, "h": 0.34, "label": "middle-left", "level": "low"},
                                                    {"x": 0.5, "y": 0.33, "w": 0.5, "h": 0.34, "label": "middle-right", "level": "medium"},
                                                        {"x": 0.0, "y": 0.67, "w": 0.5, "h": 0.33, "label": "bottom-left", "level": "low"},
                                                            {"x": 0.5, "y": 0.67, "w": 0.5, "h": 0.33, "label": "bottom-right", "level": "low"}
                                                              ],
                                                                "likelyTool": {
                                                                    "name": "Unknown",
                                                                        "confidence": 50,
                                                                            "reasoning": "One sentence explaining why this tool was identified or not."
                                                                              }
                                                                              }`;

      // Convert messages to Anthropic format
      const anthropicMessages = [];

      for (const msg of messages) {
              if (typeof msg.content === "string") {
                        anthropicMessages.push({ role: msg.role, content: msg.content });
              } else if (Array.isArray(msg.content)) {
                        const parts = [];
                        for (const block of msg.content) {
                                    if (block.type === "text") {
                                                  parts.push({ type: "text", text: block.text });
                                    } else if (block.type === "image" && block.source) {
                                                  if (block.source.type === "base64") {
                                                                  parts.push({
                                                                                    type: "image",
                                                                                    source: {
                                                                                                        type: "base64",
                                                                                                        media_type: block.source.media_type || "image/jpeg",
                                                                                                        data: block.source.data
                                                                                      }
                                                                  });
                                                  } else if (block.source.type === "url") {
                                                                  parts.push({
                                                                                    type: "image",
                                                                                    source: {
                                                                                                        type: "url",
                                                                                                        url: block.source.url
                                                                                      }
                                                                  });
                                                  }
                                    }
                        }
                        anthropicMessages.push({ role: msg.role, content: parts });
              }
      }

      const response = await fetch("https://api.anthropic.com/v1/messages", {
              method: "POST",
              headers: {
                        "Content-Type": "application/json",
                        "x-api-key": process.env.ANTHROPIC_API_KEY,
                        "anthropic-version": "2023-06-01"
              },
              body: JSON.stringify({
                        model: "claude-haiku-4-5",
                        system: systemPrompt,
                        messages: anthropicMessages,
                        max_tokens: max_tokens || 2000
              })
      });

      const data = await response.json();

      if (data.error) {
              console.error("Anthropic API error:", data.error);
              return res.status(500).json({ error: data.error.message });
      }

      const text = data.content?.[0]?.text || "";
        return res.status(200).json({ content: [{ type: "text", text }] });

  } catch (error) {
        return res.status(500).json({ error: "Analysis failed: " + error.message });
>>>>>>> 2a2fcb0ae1a3e05f6cc80023f25ddb326ebfcfe2
  }
}
