export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const { text } = req.body;
    if (!text || text.trim().length < 20) {
      return res.status(400).json({ error: "Text too short to analyze (minimum 20 characters)" });
    }

    const systemPrompt = `You are an expert AI-generated text detection system. Analyze the provided text and determine whether it was written by a human or generated by an AI language model (ChatGPT, Claude, Gemini, Copilot, Llama, etc.).

<<<<<<< HEAD
DETECTION SIGNALS — analyze each carefully:

1. WRITING PATTERNS: AI favors formulaic structure — numbered lists, tidy paragraphs, balanced transitions ("Furthermore", "Moreover", "In addition", "In conclusion"). Human writing is messier, more spontaneous.
2. VOCABULARY FLAGS: AI overuses certain words: "delve", "tapestry", "nuanced", "comprehensive", "multifaceted", "it's worth noting", "it's important to understand", "as an AI language model". Count and flag these.
3. BURSTINESS: Human writing has unpredictable sentence lengths — very short sentences mixed with long complex ones. AI produces uniformly medium-length, well-formed sentences. Low burstiness = AI signal.
4. PERSONAL VOICE: Humans reveal themselves — opinions, quirks, typos, digressions, personal anecdotes. AI stays generic, safe, balanced. Lack of personal voice = AI signal.
5. HEDGING: AI hedges excessively — "It's crucial to note", "This is a complex topic", "There are many perspectives", "It depends on various factors". Heavy hedging = AI signal.
6. TOPIC COVERAGE: AI tries to cover all angles comprehensively and fairly. Humans focus on what interests them and often ignore the rest.
=======
DETECTION SIGNALS:
1. WRITING PATTERNS: AI favors formulaic structure with tidy transitions like "Furthermore", "Moreover", "In conclusion". Human writing is messier and more spontaneous.
2. VOCABULARY FLAGS: AI overuses: "delve", "tapestry", "nuanced", "comprehensive", "multifaceted", "it's worth noting", "as an AI language model". Flag these.
3. BURSTINESS: Human writing mixes very short and very long sentences. AI produces uniformly medium-length sentences. Low burstiness = AI signal.
4. PERSONAL VOICE: Humans reveal opinions, quirks, digressions. AI stays generic and safe. No personal voice = AI signal.
5. HEDGING: AI hedges excessively — "It's crucial to note", "This is a complex topic". Heavy hedging = AI signal.
6. TOPIC COVERAGE: AI covers all angles comprehensively. Humans focus on what interests them.
>>>>>>> 2a2fcb0ae1a3e05f6cc80023f25ddb326ebfcfe2

SCORING:
- overallScore = probability the text is AI-generated (integer 0-100)
- verdict="AI-Generated" when overallScore 60-100
- verdict="Uncertain" when overallScore 30-59
- verdict="Likely Human" when overallScore 0-29

<<<<<<< HEAD
SIGNALS SCORING:
- writingPatterns: how formulaic/structured the writing is (0=natural, 100=AI template)
- vocabularyFlags: prevalence of AI marker words (0=clean, 100=heavily flagged)
- burstiness: sentence uniformity (0=varied/human, 100=perfectly uniform/AI)
- personalVoice: absence of personal voice (0=strong voice, 100=generic/voiceless)

Return ONLY this exact JSON (no markdown, no explanation outside JSON):
{
  "verdict": "AI-Generated",
  "overallScore": 82,
  "signals": {
    "writingPatterns": 80,
    "vocabularyFlags": 70,
    "burstiness": 75,
    "personalVoice": 85
  },
  "signalTags": ["formulaic transitions", "hedging phrases", "uniform sentence length", "no personal voice", "comprehensive coverage"],
  "explanation": "First sentence about the strongest evidence found. Second sentence about specific patterns or phrases detected. Third sentence with overall assessment.",
  "likelyModel": {
    "name": "ChatGPT / GPT-4",
    "confidence": 60,
    "reasoning": "One sentence explaining why this model or family is suspected."
  }
=======
Return ONLY this JSON (no markdown):
{
  "verdict": "AI-Generated",
  "overallScore": 82,
  "signals": { "writingPatterns": 80, "vocabularyFlags": 70, "burstiness": 75, "personalVoice": 85 },
  "signalTags": ["formulaic transitions", "hedging phrases", "uniform sentence length", "no personal voice"],
  "explanation": "First sentence about strongest evidence. Second sentence about specific patterns. Third sentence overall assessment.",
  "likelyModel": { "name": "ChatGPT / GPT-4", "confidence": 60, "reasoning": "One sentence why." }
>>>>>>> 2a2fcb0ae1a3e05f6cc80023f25ddb326ebfcfe2
}`;

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
<<<<<<< HEAD
        model: "claude-haiku-4-5-20251001",
=======
        model: "claude-haiku-4-5",
>>>>>>> 2a2fcb0ae1a3e05f6cc80023f25ddb326ebfcfe2
        system: systemPrompt,
        messages: [{ role: "user", content: `Analyze this text for AI generation:\n\n${text.trim()}` }],
        max_tokens: 1000
      })
    });

    const data = await response.json();
<<<<<<< HEAD

=======
>>>>>>> 2a2fcb0ae1a3e05f6cc80023f25ddb326ebfcfe2
    if (data.error) {
      console.error("Anthropic API error:", data.error);
      return res.status(500).json({ error: data.error.message });
    }

    const resultText = data.content?.[0]?.text || "";
    return res.status(200).json({ content: [{ type: "text", text: resultText }] });

  } catch (error) {
    return res.status(500).json({ error: "Analysis failed: " + error.message });
  }
}
