export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  try {
    const { messages, max_tokens } = req.body;

    const systemPrompt = `You are an AI-generated image detection expert with vision capabilities. Analyze images carefully and return ONLY a valid JSON object with no extra text or markdown.

CRITICAL DETECTION RULES (apply in order):
1. WATERMARKS: If you see any text watermark inside the image like "Gemini", "Google AI", "ImageFX", "DALL-E", "DALL-E", "Midjourney", "Stable Diffusion", "Adobe Firefly", "Sora", "Created with AI", "Generated by AI" set verdict="AI-Generated" and overallScore=97 immediately.
2. FACES: Hyper-smooth plastic skin, glassy eyes, impossible symmetry, perfect studio lighting = AI signal.
3. HANDS: Wrong number of fingers, fused/extra fingers, bent unnaturally = strong AI artifact.
4. BACKGROUNDS: Melting textures, smeared details, objects merging together, nonsense patterns = AI artifact.
5. TEXT IN IMAGE: Garbled, fake, or nonsense text floating in the image = AI artifact.
6. TOO PERFECT: Over-sharpened, no grain/noise, studio-perfect lighting with no imperfections = likely AI.

SCORING: overallScore = probability the image is AI-generated (integer 0-100, or -1 for unanalyzable URLs).
verdict="AI-Generated" when overallScore 60-100. verdict="Uncertain" when 30-59. verdict="Likely Real" when 0-29.
verdict="Cannot analyze URL" and overallScore=-1 ONLY for YouTube/TikTok/Instagram video page URLs.

HEATMAP: Always provide exactly 6 heatRegions covering the ENTIRE image. Use x,y,w,h as fractions 0.0-1.0.
level must be: "high" (AI artifact), "medium" (suspicious), or "low" (looks authentic).

Return ONLY this exact JSON structure with no markdown fences:
{"verdict":"AI-Generated","overallScore":85,"signals":{"artificialPatterns":80,"noiseConsistency":70,"semanticCoherence":75,"metadataAnomalies":60},"signalTags":["tag1","tag2","tag3","tag4"],"explanation":"Sentence one. Sentence two. Sentence three.","heatRegions":[{"x":0.0,"y":0.0,"w":0.5,"h":0.5,"label":"top-left","level":"high"},{"x":0.5,"y":0.0,"w":0.5,"h":0.5,"label":"top-right","level":"medium"},{"x":0.0,"y":0.33,"w":0.5,"h":0.34,"label":"mid-left","level":"low"},{"x":0.5,"y":0.33,"w":0.5,"h":0.34,"label":"mid-right","level":"medium"},{"x":0.0,"y":0.67,"w":0.5,"h":0.33,"label":"bot-left","level":"low"},{"x":0.5,"y":0.67,"w":0.5,"h":0.33,"label":"bot-right","level":"low"}],"likelyTool":{"name":"Unknown","confidence":50,"reasoning":"One sentence reason."}}`;

    const groqMessages = [{ role: "system", content: systemPrompt }];

    for (const msg of messages) {
      if (typeof msg.content === "string") {
        groqMessages.push({ role: msg.role, content: msg.content });
      } else if (Array.isArray(msg.content)) {
        const parts = [];
        for (const block of msg.content) {
          if (block.type === "text") {
            parts.push({ type: "text", text: block.text });
          } else if (block.type === "image" && block.source) {
            if (block.source.type === "base64") {
              parts.push({ type: "image_url", image_url: { url: `data:${block.source.media_type || "image/jpeg"};base64,${block.source.data}` } });
            } else if (block.source.type === "url") {
              parts.push({ type: "image_url", image_url: { url: block.source.url } });
            }
          }
        }
        groqMessages.push({ role: msg.role, content: parts });
      }
    }

    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${process.env.GROQ_API_KEY}` },
      body: JSON.stringify({ model: "meta-llama/llama-4-scout-17b-16e-instruct", messages: groqMessages, max_tokens: max_tokens || 2000, temperature: 0.1 })
    });

    const data = await response.json();
    if (data.error) { console.error("Groq error:", data.error); return res.status(500).json({ error: data.error.message }); }
    const text = data.choices?.[0]?.message?.content || "";
    return res.status(200).json({ content: [{ type: "text", text }] });
  } catch (error) {
    return res.status(500).json({ error: "Analysis failed: " + error.message });
  }
}
